---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Install updates for CentOS
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
    
  - name: Install updates for Debain based systems
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in "[Debian], [Ubuntu]"
    
- hosts: web_servers
  become: true
  tasks:

  - name: Install the Apache and php packages for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
      
  - name: Install the Apache and php packages for CentOS servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
    
- hosts: db_servers
  become: true
  tasks:
     
    - name: Install mariadb package for CentOS
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"
       
    - name: Install mariadb package for Ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
      
- hosts: file_servers
  become: true
  tasks:
    
    - name: Install samba package
      package:
        name: samba
        state: latest
    

